// Generated by gencpp from file x_msgs/X_CommandRequest.msg
// DO NOT EDIT!


#ifndef X_MSGS_MESSAGE_X_COMMANDREQUEST_H
#define X_MSGS_MESSAGE_X_COMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace x_msgs
{
template <class ContainerAllocator>
struct X_CommandRequest_
{
  typedef X_CommandRequest_<ContainerAllocator> Type;

  X_CommandRequest_()
    : command(0)  {
    }
  X_CommandRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int8_t _command_type;
  _command_type command;




  typedef boost::shared_ptr< ::x_msgs::X_CommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::x_msgs::X_CommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct X_CommandRequest_

typedef ::x_msgs::X_CommandRequest_<std::allocator<void> > X_CommandRequest;

typedef boost::shared_ptr< ::x_msgs::X_CommandRequest > X_CommandRequestPtr;
typedef boost::shared_ptr< ::x_msgs::X_CommandRequest const> X_CommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::x_msgs::X_CommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::x_msgs::X_CommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace x_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'x_msgs': ['/home/tom/x_os/src/x_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::x_msgs::X_CommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::x_msgs::X_CommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::x_msgs::X_CommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "481ac5a494c3140a2539020bd74c82c7";
  }

  static const char* value(const ::x_msgs::X_CommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x481ac5a494c3140aULL;
  static const uint64_t static_value2 = 0x2539020bd74c82c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "x_msgs/X_CommandRequest";
  }

  static const char* value(const ::x_msgs::X_CommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 command\n\
";
  }

  static const char* value(const ::x_msgs::X_CommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct X_CommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::x_msgs::X_CommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::x_msgs::X_CommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // X_MSGS_MESSAGE_X_COMMANDREQUEST_H
