// Generated by gencpp from file x_msgs/X_Command.msg
// DO NOT EDIT!


#ifndef X_MSGS_MESSAGE_X_COMMAND_H
#define X_MSGS_MESSAGE_X_COMMAND_H

#include <ros/service_traits.h>


#include <x_msgs/X_CommandRequest.h>
#include <x_msgs/X_CommandResponse.h>


namespace x_msgs
{

struct X_Command
{

typedef X_CommandRequest Request;
typedef X_CommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct X_Command
} // namespace x_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::x_msgs::X_Command > {
  static const char* value()
  {
    return "28a37da2e074d60a86413b1466cbc6e6";
  }

  static const char* value(const ::x_msgs::X_Command&) { return value(); }
};

template<>
struct DataType< ::x_msgs::X_Command > {
  static const char* value()
  {
    return "x_msgs/X_Command";
  }

  static const char* value(const ::x_msgs::X_Command&) { return value(); }
};


// service_traits::MD5Sum< ::x_msgs::X_CommandRequest> should match 
// service_traits::MD5Sum< ::x_msgs::X_Command > 
template<>
struct MD5Sum< ::x_msgs::X_CommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::x_msgs::X_Command >::value();
  }
  static const char* value(const ::x_msgs::X_CommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::x_msgs::X_CommandRequest> should match 
// service_traits::DataType< ::x_msgs::X_Command > 
template<>
struct DataType< ::x_msgs::X_CommandRequest>
{
  static const char* value()
  {
    return DataType< ::x_msgs::X_Command >::value();
  }
  static const char* value(const ::x_msgs::X_CommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::x_msgs::X_CommandResponse> should match 
// service_traits::MD5Sum< ::x_msgs::X_Command > 
template<>
struct MD5Sum< ::x_msgs::X_CommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::x_msgs::X_Command >::value();
  }
  static const char* value(const ::x_msgs::X_CommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::x_msgs::X_CommandResponse> should match 
// service_traits::DataType< ::x_msgs::X_Command > 
template<>
struct DataType< ::x_msgs::X_CommandResponse>
{
  static const char* value()
  {
    return DataType< ::x_msgs::X_Command >::value();
  }
  static const char* value(const ::x_msgs::X_CommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // X_MSGS_MESSAGE_X_COMMAND_H
